### ISSUE TITLE
Refactor current code to be more RxSwifty

### ISSUE THREAD

**Issue by mrianmerry** [mrianmerry/PTA#13]
I think it would be good to ensure that we're moving forward with code that matches the end-goal image, so refactoring what is currently in-place is something that should be done.

Now that Rx has been added, we should work on ensuring we proliferate it throughout the codebase.

**Comment by d9rad** [comment]
I suggest waiting for SwiftUI and Combine and replacing Rx with that 👀

**Comment by mrianmerry** [comment]
You make a good point!
