### ISSUE TITLE
Update Company Information

### ISSUE THREAD

**Issue by mrianmerry** [mrianmerry/PTA#17]
**Describe the bug**
The company information in the project is currently set to "WeatherBear", the placeholder name for copyright ownership. Now that the stakeholders have agreed how to proceed, this needs  to be updated accordingly.

**Expected behavior**
Company name reads as "Undersea Love", and the filename prefix reads "UL"

**Comment by d9rad** [comment]
Filename prefix notation hasn't been used in app-level code for a few years now since you have proper namespacing with modules 😬

**Comment by imerryw1-ford** [comment]
Yeah, well... I like it. 😂😂

**Comment by mrianmerry** [comment]
Yeah, well, I like it 😂😂😂

**Comment by mrianmerry** [comment]
Filename prefix removed, but the rest of the stuff has been updated in #21 💪
