### ISSUE TITLE
Pokédex view

### ISSUE THREAD

**Issue by mrianmerry** [mrianmerry/PTA#4]
Present a list of all available Pokémon that can be tapped to show details.
* Can be presented in either a new view controller, or some manner of concertina / modal view

---
_Note that we don't yet want to limit what's available in the Pokédex, but that it will eventually be required. Keep this in mind during development._

**Comment by mrianmerry** [comment]
@d9rad 
Something we can discuss on Saturday - the ease which we can make folding cells with RxSwift. 
I'll need you to update me on the RxDataSource 😉

**Comment by d9rad** [comment]
@mrianmerry folding cells are a pain to handle in any situation 😕

**Comment by mrianmerry** [comment]
@d9rad 
How would you feel about peek'n'pop detail views instead?
So a normal tap will just push a detail view, but a nice little force-touch will allow us to preview the information? Might be fun to code!

**Comment by d9rad** [comment]
Yeah, that's fine! Peek'n'pop over folding cells any day!!
